server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maven?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mapper:
  identity: mysql
  not-empty: true
  enum-as-simple-type: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.linging.dbase.base
