server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maven?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    port: 6379
    password:
    host: localhost

# tkMapper配置
mapper:
  identity: mysql
  not-empty: true
  enum-as-simple-type: true

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.linging.dbase.base

#zookeeper配置 自定义
zookeeper:
  address: 127.0.0.1:2181



